version: "3.9"
services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: "eralchemy"
      POSTGRES_USER: "eralchemy"
      POSTGRES_DB: "eralchemy"
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
